table = self.wait_element(By.ID, "ctl00_ContentPlaceHolder1_SortGridView_Items")
html = table.get_attribute("innerHTML")
_result = re.sub(r'<tr(.*?)</tr>', '', html, flags=re.DOTALL, count=1)
_result = re.sub(r'<td class="func">(.*?)disabled="disabled">(.*?)<\/td>|<span class="prefix">(.*?)</span>| title=""|">有', '', _result, flags=re.DOTALL)
_result = re.sub(r' class="detail" data-detail="', '>', _result)
_result = re.sub(r'<tbody>|<tr class="">|<tr>', '[', _result)
_result = re.sub(r'</tbody>|</tr>', ']', _result)
_result = re.sub("\'", "\\'", _result, flags=re.DOTALL)
_result = re.sub(r'<td.*?<span>|</span></td>|<td.*?href="|"\st.*?</td>', "'", _result, flags=re.DOTALL)
_result = _result.replace(r'../..', 'https://epis.cht.com.tw/epis100')
_result = _result.replace(r"''", "','")
_result = re.sub(r'\n|\t|&nbsp;|<br>|amp;|\r', '', _result)
_result = _result.replace(r'][', '],[')
if isinstance(check_currency, str):
    _result = re.sub(currency_pattern, Cs_EPIS_Contract.replace_currency, _result)
# Convert the string to a list
_result = ast.literal_eval(_result)